### ISSUE TITLE
support of static response payload

### ISSUE THREAD

**Issue by Asisranjan** [envoyproxy/nighthawk#318]
How do i configure response payload in test server so that any request to test server would return status code, header along with given response payload

Will appreciate for any help.

**Comment by oschaaf** [comment]
Sample configuration fragment from [here](https://github.com/envoyproxy/nighthawk/blob/master/source/server/README.md):

```
          - name: test-server   
            config:
              response_body_size: 10
              response_headers:
              - { header: { key: "foo", value: "bar"} }
              - { header: { key: "foo", value: "bar2"}, append: true }
              - { header: { key: "x-nh", value: "1"}}
```

You can indicate the size (10 in this example) for the response payload, but not the specific contents today. For indicating response code status, I think this will work:

```
- { header: { key: ":status", value: "202"}}
```
