### ISSUE TITLE
Nighthawk Test Server segfault with large response body and high RPS

### ISSUE THREAD

**Issue by eric846** [envoyproxy/nighthawk#794]
100 rps is ok, but 1000 rps was enough to crash the test server within seconds with a 1KB request body size.

It didn't happen for me with `-c dbg`, but it still happened with `-c opt --cxxopt=-g --cxxopt=-ggdb3`.

```
bazel build -c opt --cxxopt=-g --cxxopt=-ggdb3 :nighthawk

cat > ~/nhts.yaml <<END
static_resources:
  listeners:
    # define an origin server on :10000 that always returns "lorem ipsum..."
    - address:
        socket_address:
          address: 0.0.0.0
          port_value: 10000
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                generate_request_id: false
                codec_type: AUTO
                stat_prefix: ingress_http
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: service
                      domains:
                        - "*"
                http_filters:
                  - name: dynamic-delay
                    typed_config:
                      "@type": type.googleapis.com/nighthawk.server.ResponseOptions
                      static_delay: 0.5s
                  - name: test-server # before envoy.router because order matters!
                    typed_config:
                      "@type": type.googleapis.com/nighthawk.server.ResponseOptions
                      response_body_size: 10
                      v3_response_headers:
                        - { header: { key: "foo", value: "bar" } }
                        - {
                            header: { key: "foo", value: "bar2" },
                            append: true,
                          }
                        - { header: { key: "x-nh", value: "1" } }
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
                      dynamic_stats: false
admin:
  access_log_path: /tmp/envoy.log
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8081
layered_runtime:
  layers:
  - name: static_layer
    static_layer:
      envoy.reloadable_features.no_extension_lookup_by_name: false
END

bazel-bin/nighthawk_test_server --config-path ~/nhts.yaml &

bazel-bin/nighthawk_client --rps 100 --duration 100 --request-header 'x-nighthawk-test-server-config:{response_body_size:1024}' http://127.0.0.1:10000
(ok)

bazel-bin/nighthawk_client --rps 1000 --duration 100 --request-header 'x-nighthawk-test-server-config:{response_body_size:1024}' http://127.0.0.1:10000
...
benchmark.http_2xx                      573         183.82
...
[1]+  Segmentation fault      bazel-bin/nighthawk_test_server --config-path ~/nhts.yaml

```
